### ISSUE TITLE
"mvn package" fails during npm install

### ISSUE THREAD

**Issue by julienlau** [Siteminds/graylog-plugin-alertmanager#2]
Hi, 
Could you please specify more clearly the dependency in the README ?
For example: version of node / npm.

I cannot compile on my machine running:
node-default --version
v6.14.4
npm --version
3.10.10

The compilation gives:

```[ERROR] npm ERR! addLocal Could not install /home/jlu/src/graylog2-server/graylog2-web-interface/packages/graylog-web-plugin
[ERROR] npm ERR! Linux 4.12.14-lp150.12.16-default
[ERROR] npm ERR! argv "/home/jlu/src/graylog-plugin-alertmanager/node/node" "/home/jlu/src/graylog-plugin-alertmanager/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v6.9.2
[ERROR] npm ERR! npm  v4.0.3```

Thanks and regards,
Julien

**Comment by julienlau** [comment]
I cloned graylog-server source code and it helps, but it seems that it is still fail saying that yarn is needed to compile ?

**Comment by bjwschaap** [comment]
Hi @julienlau I'm sorry for the insanely late response. I've been away for a while... Did you manage to figure out how to build the plugin from source?

Yes, as stated in the documentation you need to check out the Graylog server source as well. Please note that this plugin was developed against graylog 2.4.5, and you should do a `git checkout 2.4.5` in the graylog2-server directory to use that release. It should not need yarn as far as I know.

Take a look at the Travis build: https://github.com/Siteminds/graylog-plugin-alertmanager/blob/master/.travis.yml
This might give you some pointers. There's also the general info from Graylog itself: http://docs.graylog.org/en/3.0/pages/plugins.html.

Let me know if there's anything else I can help you with.

**Comment by julienlau** [comment]
Hi
Thanks for the tips.
I did not manage to solve this issue in the past, but I am working on something else now.
NB: I did not remember to build against graylog-server source. This might have been the issue.

Regards
